Revamped the initial PinDoNoMatch Code and added screens under Settings and Help
WakalaDAO/wakala-interface pull request #181
Opened 2021-10-30 02:21 UTC by Kapersky1337

Have added the Recovery Phrase, Account Address, ContactSupportScreen, Help Screen and Pin Success Screen under the Settings and Help section accordingly

2021-10-30 02:43 UTC, Kapersky1337 commented
Added the Settings Screen / Main Panel just now.

2021-10-30 06:57 UTC, Alphonce-Mutebi approved these changes

2021-10-30 09:27 UTC, AbijahKaj commented on src/screens/Settings/SettingsScreen.js
> +import { Rubik_400Regular } from '@expo-google-fonts/rubik';
You don't have to query fonts like this, this might make the app crash if under certain circumstances the font takes too much time to load. Every font you'll need has already been loaded when the app starts (see App.js). Removing these lines will keep your component working.

2021-10-30 15:39 UTC, Kapersky1337 commented
Resolved.

2021-10-30 19:25 UTC, sebastiaohns commented on src/screens/Help/HelpScreen.js
> +const { height } = Dimensions.get("window");
You can get the height of the screen theme.js file
```suggestion
import { SIZES } from '../../consts/theme';

style={{ height: SIZES.height }}
```

2021-10-30 19:30 UTC, sebastiaohns requested changes
You can add styles creating a stylesheet. It's easier to maintain and you can reuse styles in differents components.

2021-10-31 08:30 UTC, Kapersky1337 commented on src/screens/Help/HelpScreen.js
> +const { height } = Dimensions.get("window");
I tried using that but somehow there are a few conflicts that I fear might happen with that. I would definitely try this moving forward. For now, I have tried using that but just defined the const as SIZES.height above and imported the SIZES from the theme. Would love to see the code implementation though. Thank you for the input, I also corrected a few issues with paths that I put wrong somehow my IDE didn't save changes so pushing that now. The screen seems to work fine!  
![image](https://user-images.githubusercontent.com/11522563/139574553-6293f65f-d531-4a00-99eb-5a4870eca227.png)

2021-10-31 12:01 UTC, steffenkrogmann commented on src/screens/Help/HelpScreen.js
> +const { height } = Dimensions.get("window");
@Kapersky1337 What specific conflicts do you fear might happen? Did you implement it and did they happen?

@sebastiaohns Can you share a code implementation for @Kapersky1337 ?

2021-10-31 13:51 UTC, AbijahKaj approved these changes

2021-10-31 13:57 UTC, AbijahKaj requested changes
As suggested by @sebastiaohns you have a lot of styles that can be reused, group it in one place, please!

2021-10-31 14:38 UTC, Kapersky1337 commented on src/screens/Help/HelpScreen.js
> +const { height } = Dimensions.get("window");
@steffenkrogmann I have understood the point, I misunderstood a point regarding the theme.js implementation where I thought clashes might happen, I mixed two things in one. 

In this scenario, I quite grasped that a stylesheet has to be created with the components that are being used again and again (for eg. text components) and group them together into a const style. 

I would go ahead and implement the following. Would ask @sebastiaohns if any issue persists.

2021-10-31 14:39 UTC, Kapersky1337 commented
Understood, will group the components and create a stylesheet accordingly.

2021-10-31 22:03 UTC, Kapersky1337 commented
Created StyleSheets and arranged the code as mentioned by @sebastiaohns and @AbijahKaj, please review the following code and accept the PR please.

2021-11-01 10:53 UTC, AbijahKaj approved these changes

2021-11-01 10:58 UTC, AbijahKaj requested changes

2021-11-01 10:58 UTC, AbijahKaj commented on src/screens/Help/HelpScreen.js
> +                                Stay put. You will soon be able to
This also should be grouped

2021-11-01 10:58 UTC, AbijahKaj commented on src/screens/Settings/PinDoNotMatch.js
> +                <View style={{ marginTop: RFPercentage(6), width: '80%', flexDirection: 'row', alignSelf: 'center', justifyContent: 'center', alignItems: 'center' }}>
This style should be grouped, it being reused

2021-11-01 10:58 UTC, AbijahKaj commented on src/screens/Settings/SettingsScreen.js
> +                    <View style={{ width: '100%', height: RFPercentage(0.1), backgroundColor: COLORS.line, marginTop: RFPercentage(8) }} />
This style is being used numerous times, please group it.

2021-11-01 10:58 UTC, AbijahKaj commented on src/screens/Settings/SettingsScreen.js
> +                    <View style={{ width: '100%', height: RFPercentage(0.08), backgroundColor: COLORS.line, marginTop: RFPercentage(2) }} />
Same thing

2021-11-01 12:29 UTC, Kapersky1337 commented on src/screens/Settings/SettingsScreen.js
> +                    <View style={{ width: '100%', height: RFPercentage(0.08), backgroundColor: COLORS.line, marginTop: RFPercentage(2) }} />
Have done.

2021-11-01 13:01 UTC, sebastiaohns approved these changes

2021-11-01 13:14 UTC, AbijahKaj approved these changes
Nice!

2021-11-01 13:14 UTC, merged