Add Celo integration logic
WakalaDAO/wakala-interface pull request #186
Opened 2021-11-06 20:38 UTC by onumengine

wrote closures for calling contract methods, subscribing to smart contract events and unsubscribing from them.

These methods should be assigned as click handlers to their respective buttons in the UI

2021-11-06 21:09 UTC, AbijahKaj requested changes
Please move files under src/features/celo_integration/ to src/utils/celo_integration/ it makes more sense and follows the already established architecture we are working with.

And please remove all the smart-contract files, there's another repository for them plus there's no need to ship the app with them.

2021-11-06 21:47 UTC, steffenkrogmann requested changes
src/features/celo_integration/ContractMethods.js

it says import marketplaceabi, i guess that is still from the dacade tutorial.

( i didnt review everything because i dont have the skills).

2021-11-07 22:15 UTC, onumengine commented
I've moved the celo integration files into utils

2021-11-07 22:56 UTC, AbijahKaj approved these changes

2021-11-07 22:57 UTC, sebastiaohns approved these changes

2021-11-08 07:12 UTC, steffenkrogmann approved these changes

2021-11-08 07:13 UTC, merged