Fixed wrong paths and updated the Settings Screens
WakalaDAO/wakala-interface pull request #188
Opened 2021-11-07 22:44 UTC by Kapersky1337

Have integrated the Settings Screens with how they're intended to, added a help screen page, fixed problems with the Account Address page having extra buttons, changed the paths to fix wrong imports and also fixed a few stylesheets that were causing problems.

2021-11-07 22:54 UTC, AbijahKaj requested changes
Your PR can't be merged, you need to fix conflicts first. Just merge with the current 'dev' branch then make your changes.

2021-11-10 15:23 UTC, Kapersky1337 commented
Have resolved the conflicts

2021-11-11 09:07 UTC, AbijahKaj approved these changes

2021-11-11 17:18 UTC, sebastiaohns approved these changes

2021-11-11 17:21 UTC, merged