Feature/Karma-protocol-integrations
WakalaDAO/wakala-interface pull request #271
Opened 2021-11-24 18:57 UTC by Alphonce-Mutebi

- Karma protocol methods

2021-11-24 19:59 UTC, AbijahKaj requested changes

2021-11-24 19:59 UTC, AbijahKaj commented on src/utils/celo-integration/ContractMethods.js
> +    this.updateKarma = async (address, amount, updateFunctionKey) => {
You have to use the karmaContract variable you just created

2021-11-24 19:59 UTC, AbijahKaj commented on src/utils/celo-integration/ContractMethods.js
> +        let txObject = await contract.methods.getKarma(address);
Same thing, the Wakala Contract doesn't have that method, so it won't work.

2021-11-24 20:10 UTC, Alphonce-Mutebi commented on src/utils/celo-integration/ContractMethods.js
> +        let txObject = await contract.methods.getKarma(address);
Good Catch! I made the changes

2021-11-24 20:15 UTC, AbijahKaj approved these changes

2021-11-24 20:49 UTC, steffenkrogmann commented on src/utils/celo-integration/ContractMethods.js
> +    this.updateKarma = async (address, amount, updateFunctionKey) => {
great review!

2021-11-25 04:28 UTC, sebastiaohns approved these changes

2021-11-25 04:28 UTC, merged